export default {
  // app
  APP_LAYOUT_MODE: "APP_LAYOUT_MODE",
  APP_NAV_THEME: "APP_NAV_THEME",
  APP_COLOR_WEAK: "APP_COLOR_WEAK",
  APP_DEVICE: "APP_DEVICE",
  APP_SIDEBAR: "APP_SIDEBAR",
  APP_CONTENT_WIDTH: "APP_CONTENT_WIDTH",
  APP_FIXED_HEADER: "APP_FIXED_HEADER",
  APP_AUTO_HIDE_HEADER: "APP_AUTO_HIDE_HEADER",

  // user
  USER_TOKEN: "USER_TOKEN",
  USER_NAME: "USER_NAME",
  USER_AVATAR: "USER_AVATAR",
  USER_ROLES: "USER_ROLES",
  USER_INFO: "USER_INFO",
}
